[project]
name = "marketing_and_sales"
version = "0.0.1"
authors = [
    { name = "Phamos EU", email = "support@phamos.eu"}
]
description = "A Frappe app for managing marketing and sales workflows."
requires-python = ">=3.8"
readme = "README.md"
license = { text = "AGPL-3.0" }
dependencies = []

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"

[tool.bench.dev-dependencies]
