[build-system]
requires = ["setuptools>=77.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "marketingandsales"
version = "0.0.1"
authors = [
    { name = "Phamos EU", email = "support@phamos.eu"}
]
description = "A Frappe app for managing marketing and sales workflows."
requires-python = ">=3.8"
readme = "README.md"
license = "AGPL-3.0"
dependencies = []

[tool.setuptools]
packages = ["marketingandsales"]

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"

[tool.bench.dev-dependencies]
